apiVersion: v1
kind: ConfigMap
metadata:
  name: taskforge-config
  namespace: taskforge
data:
  AUTH_DATABASE_URL: "postgresql+asyncpg://taskforge:taskforge_dev_password@postgres:5432/taskforge"
  TASK_DATABASE_URL: "postgresql+asyncpg://taskforge:taskforge_dev_password@postgres:5432/taskforge_tasks"
  REDIS_URL: "redis://redis:6379/0"
  RABBITMQ_URL: "amqp://taskforge:taskforge_dev_password@rabbitmq:5672/"
  KAFKA_BOOTSTRAP: "kafka:9092"
  QDRANT_URL: "http://qdrant:6333"
  DEBUG: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: taskforge-secrets
  namespace: taskforge
type: Opaque
stringData:
  POSTGRES_USER: "taskforge"
  POSTGRES_PASSWORD: "taskforge_dev_password"
  RABBITMQ_USER: "taskforge"
  RABBITMQ_PASSWORD: "taskforge_dev_password"
  JWT_SECRET_KEY: "93eef8f4ca76f1d44b969ccc7d3739977d5f036a673be5e205cf1b6e83d49f63"
