apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: taskforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: taskforge-notification-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: taskforge-config
                  key: RABBITMQ_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: taskforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: taskforge-analytics-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: taskforge-config
                  key: KAFKA_BOOTSTRAP
